classes: {
  composition: {
    style.stroke-dash: 3
  }
}

# Input messages
Events: {
  shape: page
  style.multiple: true
}
Events -> ControlAuthority.StateReducer
StateSnapshots: StateSnapshots\n+ semantic information\n+ version {
  shape: page
  style.multiple: true
}
StateSnapshots -> ControlAuthority.Combiner
Subscribe: {
  shape: page
}
Subscribe -> ControlAuthority.ReplayPublisher
Unsubscribe: {
  shape: page
}
Unsubscribe -> ControlAuthority.ReplayPublisher

# Main actor
ControlAuthority: {
  class: composition

  # Internal actors
  Combiner
  Distinct
  ReplayPublisher
  StateReducer
  Versioner

  CombinedStateSnapshot: CombinedStateSnapshot\n+ version {
    shape: page
  }
  Combiner -> CombinedStateSnapshot -> StateReducer
  DistinctStateSnapshot: StateSnapshot\n+ version {
    shape: page
  }
  Distinct -> DistinctStateSnapshot -> Versioner
  StateSnapshotWithMetaData: StateSnapshot\n+ semantic information\n+ version {
    shape: page
  }
  Versioner -> StateSnapshotWithMetaData -> ReplayPublisher
  StateSnapshot: StateSnapshot\n+ version {
    shape: page
  }
  StateReducer -> StateSnapshot -> Distinct
}

# Output messages
OutputStateSnapshot: StateSnapshot\n+ semantic information\n+ version {
  shape: page
}
ControlAuthority.ReplayPublisher -> OutputStateSnapshot -> Subscribers

# Environment actors
Subscribers: {
  style.multiple: true
}
