classes: {
  composition: {
    style.stroke-dash: 3
  }
}

# Input messages
Events: {
  shape: page
  style.multiple: true
}
Events -> DirectAuthority.StateReducer
StateSnapshots: StateSnapshots\n+ semantic information\n+ version {
  shape: page
  style.multiple: true
}
StateSnapshots -> DirectAuthority.Combiner
Subscribe: {
  shape: page
}
Subscribe -> DirectAuthority.ReplayPublisher
Unsubscribe: {
  shape: page
}
Unsubscribe -> DirectAuthority.ReplayPublisher

# Main actor
DirectAuthority: {
  class: composition

  # Internal actors
  Combiner
  Distinct
  ReplayPublisher
  StateReducer
  Versioner

  CombinedStateSnapshot: CombinedStateSnapshot\n+ version {
    shape: page
  }
  Combiner -> CombinedStateSnapshot -> StateReducer
  DistinctStateSnapshot: StateSnapshot\n+ version {
    shape: page
  }
  Distinct -> DistinctStateSnapshot -> Versioner
  StateSnapshot: StateSnapshot\n+ version {
    shape: page
  }
  StateReducer -> StateSnapshot -> Distinct
  StateSnapshotWithMetaData: StateSnapshot\n+ semantic information\n+ version {
    shape: page
  }
  Versioner -> StateSnapshotWithMetaData -> ReplayPublisher
}

# Output messages
OutputStateSnapshot: StateSnapshot\n+ semantic information\n+ version {
  shape: page
}
DirectAuthority.ReplayPublisher -> OutputStateSnapshot -> Subscribers

# Environment actors
Subscribers: {
  style.multiple: true
}
